Ensure a more-easily visible job-label

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,15 +7,6 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  lint:
-    runs-on: windows-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Run PSScriptAnalyzer
-        shell: pwsh
-        run: |
-          Invoke-ScriptAnalyzer -Path ./ -Recurse -Severity Error -EnableExit
-
   windows:
     uses: plus3it/actions-workflows/.github/workflows/test-salt-windows.yml@00ff10246f901f01818db412fa99124dbed4a00c
     strategy:
@@ -32,3 +23,21 @@ jobs:
       salt-os-version: ${{ matrix.os_version }}
       salt-state: ${{ matrix.salt_state }}
       salt-pillar-root: ${{ matrix.salt_pillar_root }}
+
+  lint_powershell:
+    name: PowerShell Linting
+    runs-on: windows-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Run PSScriptAnalyzer
+        shell: pwsh
+        run: |
+          # This installs the module if it's missing and runs the scan
+          Get-Module -ListAvailable PSScriptAnalyzer | Import-Module
+          $results = Invoke-ScriptAnalyzer -Path ./ -Recurse -Severity Error
+          if ($results) {
+              $results | Format-Table
+              exit 1 # Fails the PR check if errors are found
+          }
